name: Build
on:
  push:
    branches: [ 'trunk' ]

jobs:
  update_mirrors:
    name: Push to desktop mirror
    runs-on: ubuntu-latest

    if: github.event_name == 'push' && github.repository == 'Automattic/wp-calypso'

    steps:
      - name: Push to wp-desktop repository
        uses: Automattic/action-push-to-mirrors@v1
        with:
          token: ${{ secrets.WP_DESKTOP_API_TOKEN_GITHUB }}
          username: wp-desktop
          working-directory: ${{ github.workspace }}/desktop
        timeout-minutes: 5